llms:
- name: qwen/qwen3.8-27b
  api_base: http://192.168.1.4:1234/v1
  api_key: test
  model: qwen/qwen3.8-27b
  temperature: 0.0
- name: qwen/qwen3.6-35b-a3b
  api_base: http://192.168.1.122:1234/v1
  api_key: test
  model: qwen/qwen3.6-35b-a3b
  temperature: 0.0
- name: google/gemma-4-12b-qat
  api_base: http://192.168.1.57:1234/v1
  api_key: test
  model: google/gemma-4-12b-qat
  temperature: 0.0
roles:
  judge: qwen/qwen3.8-27b
  prompts: google/gemma-4-12b-qat
hl: true
max_attempts: 30
